### ISSUE TITLE
To-dos 

### ISSUE THREAD

**Issue by mike-mendoza** [TUDelft-CITG/learn-python#8]
Change the urls of images that are located at [mike's GitHub repo](https://github.com/mike-mendoza/Bivariate_NPBN_workshop_files/tree/main/files_pyhton_book_test)  once the learn-python repo becomes public.

**Comment by rlanzafame** [comment]
@mike-mendoza can you double check these to-do's and turn any individual ones that remain into a new issue (apply milestone Publish Summer 2023 Version to each)
